# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(531, 693)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.comboBox_scale = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_scale.setGeometry(QtCore.QRect(10, 20, 85, 27))
        self.comboBox_scale.setObjectName("comboBox_scale")
        self.comboBox_scale.addItem("")
        self.comboBox_scale.addItem("")
        self.comboBox_scale.addItem("")
        self.comboBox_scale.addItem("")
        self.comboBox_scale.addItem("")
        self.comboBox_scale.addItem("")
        self.comboBox_scale.addItem("")
        self.comboBox_scale.addItem("")
        self.comboBox_scale.addItem("")
        self.comboBox_scale.addItem("")
        self.checkBox_car = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_car.setGeometry(QtCore.QRect(120, 0, 97, 22))
        self.checkBox_car.setObjectName("checkBox_car")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 67, 17))
        self.label_3.setObjectName("label_3")
        self.checkBox_bandpass = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_bandpass.setGeometry(QtCore.QRect(120, 20, 141, 22))
        self.checkBox_bandpass.setObjectName("checkBox_bandpass")
        self.pushButton_bp = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_bp.setGeometry(QtCore.QRect(410, 17, 99, 26))
        self.pushButton_bp.setObjectName("pushButton_bp")
        self.spinBox_time = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_time.setGeometry(QtCore.QRect(10, 80, 85, 27))
        self.spinBox_time.setMinimum(1)
        self.spinBox_time.setProperty("value", 10)
        self.spinBox_time.setObjectName("spinBox_time")
        self.doubleSpinBox_hp = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.doubleSpinBox_hp.setGeometry(QtCore.QRect(250, 17, 69, 27))
        self.doubleSpinBox_hp.setMinimum(0.1)
        self.doubleSpinBox_hp.setMaximum(1000.0)
        self.doubleSpinBox_hp.setSingleStep(1.0)
        self.doubleSpinBox_hp.setProperty("value", 1.0)
        self.doubleSpinBox_hp.setObjectName("doubleSpinBox_hp")
        self.doubleSpinBox_lp = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.doubleSpinBox_lp.setGeometry(QtCore.QRect(330, 17, 69, 27))
        self.doubleSpinBox_lp.setMinimum(1.0)
        self.doubleSpinBox_lp.setMaximum(1000.0)
        self.doubleSpinBox_lp.setSingleStep(1.0)
        self.doubleSpinBox_lp.setProperty("value", 50.0)
        self.doubleSpinBox_lp.setObjectName("doubleSpinBox_lp")
        self.checkBox_showTID = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_showTID.setGeometry(QtCore.QRect(120, 60, 161, 22))
        self.checkBox_showTID.setObjectName("checkBox_showTID")
        self.checkBox_showLPT = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_showLPT.setGeometry(QtCore.QRect(120, 80, 151, 22))
        self.checkBox_showLPT.setObjectName("checkBox_showLPT")
        self.checkBox_showKey = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_showKey.setGeometry(QtCore.QRect(120, 100, 151, 22))
        self.checkBox_showKey.setObjectName("checkBox_showKey")
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(100, -1, 21, 133))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setGeometry(QtCore.QRect(110, 45, 421, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralWidget)
        self.line_3.setGeometry(QtCore.QRect(290, 57, 21, 75))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.pushButton_stoprec = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_stoprec.setGeometry(QtCore.QRect(310, 95, 201, 28))
        self.pushButton_stoprec.setObjectName("pushButton_stoprec")
        self.pushButton_rec = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_rec.setGeometry(QtCore.QRect(460, 60, 51, 27))
        self.pushButton_rec.setObjectName("pushButton_rec")
        self.lineEdit_recFilename = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_recFilename.setGeometry(QtCore.QRect(310, 60, 141, 27))
        self.lineEdit_recFilename.setObjectName("lineEdit_recFilename")
        self.table_channels = QtWidgets.QTableWidget(self.centralWidget)
        self.table_channels.setGeometry(QtCore.QRect(4, 131, 525, 503))
        self.table_channels.setMaximumSize(QtCore.QSize(529, 16777215))
        self.table_channels.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_channels.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.table_channels.setShowGrid(False)
        self.table_channels.setObjectName("table_channels")
        self.table_channels.setColumnCount(0)
        self.table_channels.setRowCount(0)
        self.table_channels.horizontalHeader().setVisible(False)
        self.table_channels.horizontalHeader().setHighlightSections(False)
        self.table_channels.verticalHeader().setVisible(False)
        self.table_channels.verticalHeader().setHighlightSections(False)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 531, 20))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox_scale.setItemText(0, _translate("MainWindow", "1uV"))
        self.comboBox_scale.setItemText(1, _translate("MainWindow", "10uV"))
        self.comboBox_scale.setItemText(2, _translate("MainWindow", "25uV"))
        self.comboBox_scale.setItemText(3, _translate("MainWindow", "50uV"))
        self.comboBox_scale.setItemText(4, _translate("MainWindow", "100uV"))
        self.comboBox_scale.setItemText(5, _translate("MainWindow", "250uV"))
        self.comboBox_scale.setItemText(6, _translate("MainWindow", "500uV"))
        self.comboBox_scale.setItemText(7, _translate("MainWindow", "1mV"))
        self.comboBox_scale.setItemText(8, _translate("MainWindow", "2.5mV"))
        self.comboBox_scale.setItemText(9, _translate("MainWindow", "100mV"))
        self.checkBox_car.setText(_translate("MainWindow", "CAR Filter"))
        self.label_2.setText(_translate("MainWindow", "Time (s)"))
        self.label_3.setText(_translate("MainWindow", "Scale"))
        self.checkBox_bandpass.setText(_translate("MainWindow", "Bandpass Filter"))
        self.pushButton_bp.setText(_translate("MainWindow", "Apply BP"))
        self.checkBox_showTID.setText(_translate("MainWindow", "Show TID events"))
        self.checkBox_showLPT.setText(_translate("MainWindow", "Show LPT events"))
        self.checkBox_showKey.setText(_translate("MainWindow", "Show Key events"))
        self.pushButton_stoprec.setText(_translate("MainWindow", "Stop REC"))
        self.pushButton_rec.setText(_translate("MainWindow", "REC"))


