.. This (-*- rst -*-) format file contains commonly used link targets and name
   substitutions.  It may be included in many files, therefore it should only
   contain link targets and name substitutions. Try grepping for "^\.\. _" to
   find plausible candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for:
   nipy, NIPY, Nipy, etc...


.. project

.. _project pypi: https://pypi.org/project/bsl/
.. _project github: https://github.com/fcbg-hnp-meeg/bsl
.. _project license: https://github.com/fcbg-hnp-meeg/bsl/blob/main/LICENSE


.. fcbg

.. _fcbg hnp: https://hnp.fcbg.ch/
.. _fcbg hnp gh-demo-rt: https://github.com/fcbg-hnp-meeg/demo-realtime


.. license

.. _MIT license: https://opensource.org/licenses/MIT


.. lsl

.. _lsl intro: https://labstreaminglayer.readthedocs.io/info/intro.html
.. _lsl lib c++: https://github.com/sccn/liblsl
.. _lsl python: https://github.com/labstreaminglayer/pylsl

.. mne

.. _mne stable: https://mne.tools/stable/index.html
.. _mne bids: https://mne.tools/mne-bids/stable/index.html
.. _mne connectivity: https://mne.tools/mne-connectivity/stable/index.html
.. _mne icalabel: https://mne.tools/mne-icalabel/dev/index.html
.. _autoreject: https://autoreject.github.io/stable/index.html


.. numpy

.. _numpy: https://numpy.org/


.. psychopy

.. _psychopy: https://www.psychopy.org/


.. scipy

.. _scipy: https://scipy.org/


.. sklearn

.. _scikit-learn: https://scikit-learn.org/stable/
