.. This (-*- rst -*-) format file contains commonly used link targets and name
   substitutions.  It may be included in many files, therefore it should only
   contain link targets and name substitutions. Try grepping for "^\.\. _" to
   find plausible candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for:
   nipy, NIPY, Nipy, etc...


.. fcbg

.. _fcbg hnp: https://hnp.fcbg.ch/


.. lsl

.. _lsl intro: https://labstreaminglayer.readthedocs.io/info/intro.html
.. _lsl lib c++: https://github.com/sccn/liblsl
.. _lsl python: https://github.com/labstreaminglayer/pylsl


.. mne

.. _mne stable: https://mne.tools/stable/index.html


.. project

.. _project pypi: https://pypi.org/project/mne-lsl/
