.. This (-*- rst -*-) format file contains commonly used link targets
   and name substitutions.  It may be included in many files,
   therefore it should only contain link targets and name
   substitutions.  Try grepping for "^\.\. _" to find plausible
   candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for
   nipy, NIPY, Nipy, etc...


.. mne

.. _`mne`: https://mne.tools/stable/index.html
.. _`mne-python`: https://mne.tools/stable/index.html
.. _`mne-python GitHub`: https://github.com/mne-tools/mne-python
.. _`mne-python sample dataset`: https://s3.amazonaws.com/mne-python/datasets/MNE-sample-data-processed.tar.gz


.. numpy

.. _numpy: http://www.numpy.org
.. _`numpy github`: http://github.com/numpy/numpy
.. _`numpy style`: https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt
.. _`numpy mailing list`: http://mail.scipy.org/mailman/listinfo/numpy-discussion


.. scipy

.. _scipy: http://www.scipy.org
.. _`scipy github`: http://github.com/scipy/scipy
.. _`scipy mailing list`: http://mail.scipy.org/mailman/listinfo/scipy-dev


.. pylsl

.. _pylsl: https://github.com/labstreaminglayer/liblsl-Python
.. _liblsl: https://github.com/sccn/liblsl/releases
.. _`liblsl release page`: https://github.com/sccn/liblsl/releases


.. pyqt

.. _pyqt5: https://www.riverbankcomputing.com/software/pyqt/
.. _pyqtgraph: https://www.pyqtgraph.org/


.. psychopy

.. _psychopy: https://www.psychopy.org/


.. pyserial

.. _pyserial: https://github.com/pyserial/pyserial


.. Pytest

.. _pytest: https://docs.pytest.org/


.. Flake8

.. _Flake8: http://flake8.pycqa.org/


.. git stuff

.. _github: https://github.com
.. _GitHub Help: https://help.github.com
.. _pro git book: https://git-scm.com/book/
.. _git clone: http://schacon.github.com/git/git-clone.html
.. _git checkout: https://schacon.github.io/git/git-checkout.html
.. _git commit: https://schacon.github.io/git/git-commit.html
.. _git push: https://schacon.github.io/git/git-push.html
.. _git pull: https://schacon.github.io/git/git-pull.html
.. _git add: https://schacon.github.io/git/git-add.html
.. _git status: https://schacon.github.io/git/git-status.html
.. _git diff: https://schacon.github.io/git/git-diff.html
.. _git log: https://schacon.github.io/git/git-log.html
.. _git branch: https://schacon.github.io/git/git-branch.html
.. _git remote: https://schacon.github.io/git/git-remote.html
.. _git rebase: https://schacon.github.io/git/git-rebase.html
.. _git config: https://schacon.github.io/git/git-config.html


.. other stuff

.. _python: http://www.python.org
.. _Brain Imaging Data Structure: https://bids.neuroimaging.io/


.. python packages

.. _pep8: https://pypi.org/project/pep8/
.. _pyflakes: https://pypi.org/project/pyflakes
.. _coverage: https://pypi.python.org/pypi/coverage
.. _scikit-learn: https://scikit-learn.org/stable/
.. _matplotlib: https://matplotlib.org/
.. _sphinx: https://www.sphinx-doc.org/
.. _pandas: https://pandas.pydata.org/
.. _tqdm: https://tqdm.github.io/
.. _pooch: https://www.fatiando.org/pooch/latest/
