name: publish

on:
  release:
    types: [published]

jobs:
  pypi:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install linux dependencies
        run: |
          sudo apt update
          sudo apt install -y libpugixml-dev qtbase5-dev qt5-qmake
      - name: Install dependencies
        run: |
          python -m pip install --progress-bar off --upgrade pip setuptools wheel
          python -m pip install --progress-bar off .[build]
      - name: Display system information
        run: bsl-sys_info --developer
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN  }}
        run: |
          python -m build
          twine upload dist/*
